
// src/services/backend.ts
'use client';

import { db, auth as firebaseAuth, storage as firebaseStorage } from '@/lib/firebase'; // Ensure firebaseStorage is imported
import {
  collection,
  doc,
  setDoc,
  getDoc,
  getDocs,
  Timestamp,
  serverTimestamp,
  deleteDoc,
  updateDoc,
  writeBatch,
  query,
  where,
  limit,
  orderBy,
  addDoc,
  FieldValue,
  deleteField,
  runTransaction
} from "firebase/firestore";
import { getStorage, ref, uploadString, getDownloadURL, deleteObject } from "firebase/storage";
import { parseISO, isValid } from 'date-fns';
import type { PosConnectionConfig } from './pos-integration/pos-adapter.interface';
import firebaseApp from '@/lib/firebase';


// Firestore Collection Names
export const USERS_COLLECTION = "users";
export const INVENTORY_COLLECTION = "inventoryProducts";
export const DOCUMENTS_COLLECTION = "documents";
export const SUPPLIERS_COLLECTION = "suppliers";
export const OTHER_EXPENSES_COLLECTION = "otherExpenses";
export const EXPENSE_CATEGORIES_COLLECTION = "expenseCategories";
export const EXPENSE_TEMPLATES_COLLECTION = "expenseTemplates"; // For Firestore based templates
export const USER_SETTINGS_COLLECTION = "userSettings";

// localStorage keys (primarily for temporary data or UI preferences not in UserSettings)
export const TEMP_DATA_KEY_PREFIX = 'invoTrackTempScanData_';
export const MAX_SCAN_RESULTS_SIZE_BYTES = 0.4 * 1024 * 1024; // 0.4MB
export const MAX_INVOICE_HISTORY_ITEMS = 10; // For client-side display of recent uploads
export const KPI_PREFERENCES_STORAGE_KEY_BASE = 'invoTrack_kpiPreferences_v2';
export const QUICK_ACTIONS_PREFERENCES_STORAGE_KEY_BASE = 'invoTrack_quickActionsPreferences_v1';


export interface User {
  id: string;
  username?: string | null;
  email?: string | null;
  createdAt?: Timestamp | FieldValue;
  lastLoginAt?: Timestamp | FieldValue;
}

export interface Product {
  id: string;
  userId?: string;
  catalogNumber: string;
  description: string;
  shortName?: string | null;
  barcode?: string | null;
  quantity: number;
  unitPrice: number;
  salePrice?: number | null;
  lineTotal: number;
  minStockLevel?: number | null;
  maxStockLevel?: number | null;
  imageUrl?: string | null;
  _originalId?: string; // Used during editing to track original item if ID changes
  lastUpdated?: Timestamp | FieldValue;
}

export interface InvoiceHistoryItem {
  id: string; // Firestore document ID
  userId: string;
  originalFileName: string;
  generatedFileName: string; // Name generated by system (e.g., Supplier_InvoiceNumber)
  uploadTime: string | Timestamp; // ISO string or Firestore Timestamp
  status: 'pending' | 'processing' | 'completed' | 'error';
  documentType: 'deliveryNote' | 'invoice' | 'paymentReceipt';
  supplierName?: string | null;
  invoiceNumber?: string | null;
  invoiceDate?: string | Timestamp | null;
  totalAmount?: number | null;
  paymentMethod?: string | null;
  paymentDueDate?: string | Timestamp | null;
  paymentStatus: 'paid' | 'unpaid' | 'pending_payment';
  paymentReceiptImageUri?: string | null; // URL from Firebase Storage
  originalImagePreviewUri?: string | null; // URL from Firebase Storage
  compressedImageForFinalRecordUri?: string | null; // URL from Firebase Storage
  errorMessage?: string | null;
  linkedDeliveryNoteId?: string | null; // For linking receipts to delivery notes/invoices
  _displayContext?: 'image_only' | 'full_details'; // UI hint for modals/sheets
}


export interface SupplierSummary {
  id: string;
  userId: string;
  name: string;
  invoiceCount: number;
  totalSpent: number;
  phone?: string | null;
  email?: string | null;
  paymentTerms?: string | null;
  lastActivityDate?: string | Timestamp | null; // ISO string or Firestore Timestamp
  createdAt: Timestamp | FieldValue;
}

export interface AccountantSettings {
  name?: string | null;
  email?: string | null;
  phone?: string | null;
}

export interface KpiPreferences {
  visibleKpiIds: string[];
  kpiOrder: string[];
}

export interface QuickActionPreferences {
  visibleQuickActionIds: string[];
  quickActionOrder: string[];
}
export interface UserSettings {
  userId: string;
  reminderDaysBefore?: number | null;
  posSystemId?: string | null;
  posConfig?: PosConnectionConfig | null;
  accountantSettings?: AccountantSettings | null;
  monthlyBudget?: number | null;
  kpiPreferences?: KpiPreferences | null;
  quickActionPreferences?: QuickActionPreferences | null;
}

export interface OtherExpense {
  id: string;
  userId: string;
  description: string;
  amount: number;
  date: string | Timestamp; // ISO string or Firestore Timestamp
  category: string; // User-facing category name
  _internalCategoryKey?: string | null; // For mapping to default/internal keys
  categoryId?: string | null; // FK to ExpenseCategories collection
}

export interface ExpenseCategory {
  id: string;
  userId: string;
  name: string; // User-defined name
  internalKey: string; // System key, e.g., "electricity", "rent" (unique per user)
  isFixed?: boolean; // If it's a typically fixed expense like rent
  defaultAmount?: number | null; // For pre-filling fixed expenses
  createdAt: Timestamp | FieldValue;
}

export interface ExpenseTemplate {
  id: string;
  userId: string;
  name: string;
  categoryKey: string; // internalKey of the category
  description: string;
  amount: number;
  createdAt: Timestamp | FieldValue;
}


// --- Helper function to get localStorage keys with userId ---
export const getStorageKey = (baseKey: string, userId?: string): string => {
  if (!userId) {
    if ([KPI_PREFERENCES_STORAGE_KEY_BASE, QUICK_ACTIONS_PREFERENCES_STORAGE_KEY_BASE].includes(baseKey)) {
        return baseKey;
    }
    console.warn(`[getStorageKey] Called for baseKey "${baseKey}" without a userId, but it's not a shared preference key. This might lead to data collision or incorrect access.`);
    return `${baseKey}_SHARED_OR_NO_USER`; // Fallback, but should be avoided for user-specific data
  }
  return `${baseKey}_${userId}`;
};

export const getStoredData = <T>(keyBase: string, userId?: string, defaultDataIfNoUserOrError: T | T[] = []): T | T[] => {
  if (typeof window === 'undefined') return defaultDataIfNoUserOrError;
  const storageKey = getStorageKey(keyBase, userId);
  try {
    const stored = localStorage.getItem(storageKey);
    if (stored) {
      return JSON.parse(stored);
    }
    return defaultDataIfNoUserOrError;
  } catch (error) {
    console.error(`Error reading ${storageKey} from localStorage:`, error);
    return defaultDataIfNoUserOrError;
  }
};

const saveStoredData = (keyBase: string, data: any, userId?: string): boolean => {
  if (typeof window === 'undefined') return false;
  const storageKey = getStorageKey(keyBase, userId);
  try {
    localStorage.setItem(storageKey, JSON.stringify(data));
    return true;
  } catch (error: any) {
    console.error(`Error writing to localStorage for key ${storageKey}:`, error);
    if (error instanceof DOMException && (error.name === 'QuotaExceededError' || error.message.includes('exceeded the quota'))) {
      console.warn(`Quota exceeded for key ${storageKey}. Attempting to clear old temporary scan data and retry...`);
      try {
        clearOldTemporaryScanData(true, userId); // Emergency clear for this user
        localStorage.setItem(storageKey, JSON.stringify(data));
        console.log(`Successfully saved to localStorage after cleanup for key ${storageKey}`);
        return true;
      } catch (retryError) {
        console.error(`Error writing ${storageKey} to localStorage even after cleanup:`, retryError);
        const quotaError = new Error(`Failed to save data to localStorage after cleanup due to storage quota: ${(retryError as Error).message}`);
        (quotaError as any).isQuotaError = true;
        throw quotaError;
      }
    } else {
        const genericError = new Error(`Failed to save data to localStorage: ${(error as Error).message}`);
        (genericError as any).isQuotaError = false;
        throw genericError;
    }
  }
};

export function sanitizeForFirestore<T extends object>(data: T): T {
  const sanitizedData = { ...data } as Record<string, any>;
  for (const key in sanitizedData) {
    if (sanitizedData[key] === undefined) {
      sanitizedData[key] = null; // Firestore prefers null over undefined for absent fields
    }
  }
  return sanitizedData as T;
}

// --- Firebase Storage Helper Functions ---
export async function uploadImageToFirebaseStorage(
  base64Data: string,
  filePath: string
): Promise<string> {
  if (!firebaseStorage) { // Check if storage instance from firebase.ts is available
    console.error("Firebase Storage is not initialized in uploadImageToFirebaseStorage.");
    throw new Error("Firebase Storage not initialized.");
  }
  const storageRef = ref(firebaseStorage, filePath);
  try {
    console.log(`[Backend] Attempting to upload image to Firebase Storage at path: ${filePath}`);
    const snapshot = await uploadString(storageRef, base64Data, 'data_url');
    const downloadURL = await getDownloadURL(snapshot.ref);
    console.log(`[Backend] Image uploaded successfully to Firebase Storage: ${downloadURL}`);
    return downloadURL;
  } catch (error) {
    console.error("[Backend] Error uploading image to Firebase Storage:", error);
    throw error;
  }
}

export async function deleteImageFromFirebaseStorage(fileUrl?: string | null): Promise<void> {
  if (!firebaseStorage) {
    console.error("Firebase Storage is not initialized in deleteImageFromFirebaseStorage.");
    return;
  }
  if (!fileUrl || !fileUrl.startsWith('https://firebasestorage.googleapis.com/')) {
    return;
  }
  
  try {
    const storageRef = ref(firebaseStorage, fileUrl);
    await deleteObject(storageRef);
    console.log(`[Backend] Image deleted from Firebase Storage: ${fileUrl}`);
  } catch (error: any) {
    if (error.code === 'storage/object-not-found') {
      console.warn(`[Backend] Image not found for deletion, possibly already deleted: ${fileUrl}`);
    } else {
      console.error("[Backend] Error deleting image from Firebase Storage:", error);
    }
  }
}


// --- User Management (Firestore) ---
export async function saveUserToFirestore(userData: User): Promise<void> {
  if (!db) {
    console.error("Firestore (db) is not initialized in saveUserToFirestore.");
    throw new Error("Database not initialized.");
  }
  if (!userData.id) {
    console.error("User ID is missing for saveUserToFirestore.");
    throw new Error("User ID is missing.");
  }
  
  const userRef = doc(db, USERS_COLLECTION, userData.id);
  const dataToSave: Partial<User> = {
    email: userData.email || null,
    username: userData.username || null,
  };
  
  try {
    const userDoc = await getDoc(userRef);
    if (!userDoc.exists()) {
      dataToSave.createdAt = serverTimestamp();
      console.log(`[saveUserToFirestore] User ${userData.id} does not exist, setting createdAt.`);
    }
    dataToSave.lastLoginAt = serverTimestamp();
    console.log(`[saveUserToFirestore] Saving/updating user ${userData.id} with data:`, dataToSave);
    await setDoc(userRef, sanitizeForFirestore(dataToSave), { merge: true });
    console.log(`[saveUserToFirestore] User ${userData.id} saved/updated successfully.`);
  } catch (error) {
    console.error("[saveUserToFirestore] Error saving user to Firestore:", error);
    throw error;
  }
}

export async function getUserFromFirestore(userId: string): Promise<User | null> {
  if (!db) {
    console.error("Firestore (db) is not initialized in getUserFromFirestore.");
    return null;
  }
  if (!userId) {
    console.warn("getUserFromFirestore called without userId");
    return null;
  }
  
  const userRef = doc(db, USERS_COLLECTION, userId);
  try {
    const docSnap = await getDoc(userRef);
    if (docSnap.exists()) {
      const data = docSnap.data();
      return { 
        id: docSnap.id, 
        ...data,
        email: data.email || null, 
        username: data.username || null, 
        createdAt: data.createdAt instanceof Timestamp ? data.createdAt : undefined, 
        lastLoginAt: data.lastLoginAt instanceof Timestamp ? data.lastLoginAt : undefined, 
      } as User;
    }
    console.log(`[getUserFromFirestore] No user found with ID: ${userId}`);
    return null;
  } catch (error) {
    console.error("Error fetching user from Firestore:", error);
    throw error; 
  }
}

// --- Inventory Products (Firestore) ---
export async function getProductsService(userId: string): Promise<Product[]> {
  if (!db) {
    console.error("Firestore (db) is not initialized in getProductsService.");
    return [];
  }
  if (!userId) {
    console.warn("getProductsService called without userId. Returning empty array.");
    return [];
  }
  
  const productsQuery = query(collection(db, INVENTORY_COLLECTION), where("userId", "==", userId), orderBy("shortName"));
  try {
    const snapshot = await getDocs(productsQuery);
    return snapshot.docs.map(docSnap => ({ 
        id: docSnap.id, 
        ...docSnap.data(),
        lastUpdated: docSnap.data().lastUpdated instanceof Timestamp ? docSnap.data().lastUpdated : undefined,
    } as Product));
  } catch (error) {
    console.error("Error fetching products from Firestore:", error);
    if ((error as any).message && (error as any).message.includes("The query requires an index")) {
        console.error("Firestore missing index error for products. Please create the suggested index in your Firebase console (check browser console for the link).");
    }
    throw error;
  }
}

export async function getProductByIdService(productId: string, userId: string): Promise<Product | null> {
  if (!db || !userId) return null;
  const productRef = doc(db, INVENTORY_COLLECTION, productId);
  try {
    const docSnap = await getDoc(productRef);
    if (docSnap.exists() && docSnap.data().userId === userId) {
      const data = docSnap.data();
      return { 
          id: docSnap.id, 
          ...data,
          lastUpdated: data.lastUpdated instanceof Timestamp ? data.lastUpdated : undefined,
      } as Product;
    }
    return null;
  } catch (error) {
    console.error(`Error fetching product ${productId} from Firestore:`, error);
    throw error;
  }
}

export async function updateProductService(productId: string, updatedData: Partial<Omit<Product, 'id' | 'userId'>>, userId: string): Promise<void> {
  if (!db || !userId) throw new Error("DB not initialized or User ID missing.");
  const productRef = doc(db, INVENTORY_COLLECTION, productId);
  const dataToUpdate: Partial<Omit<Product, 'id' | 'userId'>> & { lastUpdated: FieldValue } = {
    ...sanitizeForFirestore(updatedData),
    lastUpdated: serverTimestamp()
  };

  try {
    const productDoc = await getDoc(productRef);
    if (!productDoc.exists() || productDoc.data().userId !== userId) {
      throw new Error("Permission denied or product not found for update.");
    }
    await updateDoc(productRef, dataToUpdate);
  } catch (error) {
    console.error(`Error updating product ${productId} in Firestore:`, error);
    throw error;
  }
}

export async function deleteProductService(productId: string, userId: string): Promise<void> {
  if (!db || !userId) throw new Error("DB not initialized or User ID missing.");
  const productRef = doc(db, INVENTORY_COLLECTION, productId);
  try {
    const productDoc = await getDoc(productRef);
    if (!productDoc.exists() || productDoc.data().userId !== userId) {
      throw new Error("Permission denied or product not found for deletion.");
    }
    await deleteDoc(productRef);
  } catch (error) {
    console.error(`Error deleting product ${productId} from Firestore:`, error);
    throw error;
  }
}

export async function deleteCollectionByUserId(collectionName: string, userId: string): Promise<void> {
  if (!db || !userId) throw new Error(`DB not initialized or User ID missing for deleteCollectionByUserId: ${collectionName}`);
  
  const q = query(collection(db, collectionName), where("userId", "==", userId));
  const snapshot = await getDocs(q);
  if (snapshot.empty) {
    console.log(`[deleteCollectionByUserId] No documents to delete in ${collectionName} for user ${userId}.`);
    return;
  }

  const batch = writeBatch(db);
  snapshot.docs.forEach(docSnap => { // Changed doc to docSnap to avoid conflict
    batch.delete(docSnap.ref);
  });
  await batch.commit();
  console.log(`[deleteCollectionByUserId] All documents in ${collectionName} for user ${userId} have been deleted.`);
}

export async function clearInventoryService(userId: string): Promise<void> {
  await deleteCollectionByUserId(INVENTORY_COLLECTION, userId);
}

// --- Documents (Invoices/Delivery Notes - Firestore) ---
export async function getInvoicesService(userId: string): Promise<InvoiceHistoryItem[]> {
  if (!db) {
    console.error("Firestore (db) is not initialized in getInvoicesService.");
    return [];
  }
  if (!userId) {
    console.warn("getInvoicesService called without userId. Returning empty array.");
    return [];
  }
  
  const documentsQuery = query(collection(db, DOCUMENTS_COLLECTION), where("userId", "==", userId), orderBy("uploadTime", "desc"));
  try {
    const snapshot = await getDocs(documentsQuery);
    return snapshot.docs.map(docSnap => {
        const data = docSnap.data();
        const convertTimestampToString = (field: any): string | null => {
            if (field instanceof Timestamp) return field.toDate().toISOString();
            if (typeof field === 'string' && isValid(parseISO(field))) return field; 
            if (field instanceof Date && isValid(field)) return field.toISOString(); 
            return null; 
        };
        return {
            id: docSnap.id, 
            ...data,
            uploadTime: convertTimestampToString(data.uploadTime), 
            invoiceDate: convertTimestampToString(data.invoiceDate),
            paymentDueDate: convertTimestampToString(data.paymentDueDate),
            _displayContext: data._displayContext || 'full_details', // Ensure _displayContext has a default
        } as InvoiceHistoryItem;
    });
  } catch (error) {
    console.error("Error fetching documents from Firestore:", error);
     if ((error as any).message && (error as any).message.includes("The query requires an index")) {
        console.error("Firestore missing index error for documents. Firebase usually provides a link in the error message to create it. Check the browser console for the full error.");
    }
    throw error;
  }
}

export async function updateInvoiceService(invoiceId: string, updatedData: Partial<Omit<InvoiceHistoryItem, 'id' | 'userId'>>, userId: string): Promise<void> {
  if (!db || !userId) throw new Error("DB not initialized or User ID missing.");

  const docRef = doc(db, DOCUMENTS_COLLECTION, invoiceId);
  
  const dataToUpdate: any = { ...updatedData }; 
  const convertToTimestampIfValidString = (dateField: any): Timestamp | null => {
    if (!dateField) return null;
    if (dateField instanceof Date && isValid(dateField)) return Timestamp.fromDate(dateField); 
    if (typeof dateField === 'string' && isValid(parseISO(dateField))) {
      return Timestamp.fromDate(parseISO(dateField));
    }
    return dateField instanceof Timestamp ? dateField : null; 
  };

  if (dataToUpdate.hasOwnProperty('invoiceDate')) dataToUpdate.invoiceDate = convertToTimestampIfValidString(dataToUpdate.invoiceDate);
  if (dataToUpdate.hasOwnProperty('paymentDueDate')) dataToUpdate.paymentDueDate = convertToTimestampIfValidString(dataToUpdate.paymentDueDate);
  if (dataToUpdate.hasOwnProperty('uploadTime')) { 
    dataToUpdate.uploadTime = convertToTimestampIfValidString(dataToUpdate.uploadTime);
  }
  
  const sanitizedDataToUpdate = sanitizeForFirestore(dataToUpdate);

  try {
    const docSnap = await getDoc(docRef);
    if(!docSnap.exists() || docSnap.data().userId !== userId) {
      throw new Error("Permission denied or document not found for update.");
    }
    await updateDoc(docRef, sanitizedDataToUpdate);
  } catch (error) {
    console.error(`Error updating document ${invoiceId} in Firestore:`, error);
    throw error;
  }
}

export async function updateInvoicePaymentStatusService(invoiceId: string, paymentStatus: InvoiceHistoryItem['paymentStatus'], userId: string, paymentReceiptImageUri?: string | null): Promise<void> {
  if (!db || !userId) throw new Error("DB not initialized or User ID missing.");
  const docRef = doc(db, DOCUMENTS_COLLECTION, invoiceId);
  const updateData: any = { paymentStatus };
 
  if (paymentStatus === 'paid' && paymentReceiptImageUri !== undefined) {
    updateData.paymentReceiptImageUri = paymentReceiptImageUri; 
  } else if (paymentStatus !== 'paid') { 
    updateData.paymentReceiptImageUri = null; // Set to null if not paid or if URI is explicitly undefined
  }

  try {
     const docSnap = await getDoc(docRef);
     if(!docSnap.exists() || docSnap.data().userId !== userId) {
        throw new Error("Permission denied or document not found for payment status update.");
     }
    await updateDoc(docRef, sanitizeForFirestore(updateData));
  } catch (error) {
    console.error(`Error updating payment status for document ${invoiceId}:`, error);
    throw error;
  }
}

export async function deleteInvoiceService(invoiceId: string, userId: string): Promise<void> {
  if (!db || !userId) throw new Error("DB not initialized or User ID missing.");
  const docRef = doc(db, DOCUMENTS_COLLECTION, invoiceId);
  try {
    const docSnap = await getDoc(docRef);
    if (!docSnap.exists() || docSnap.data().userId !== userId) {
      throw new Error("Permission denied or document not found for deletion.");
    }
    // Before deleting the document, delete any associated images from Firebase Storage
    if (docSnap.data().originalImagePreviewUri) {
      await deleteImageFromFirebaseStorage(docSnap.data().originalImagePreviewUri);
    }
    if (docSnap.data().compressedImageForFinalRecordUri) {
      await deleteImageFromFirebaseStorage(docSnap.data().compressedImageForFinalRecordUri);
    }
    if (docSnap.data().paymentReceiptImageUri) {
      await deleteImageFromFirebaseStorage(docSnap.data().paymentReceiptImageUri);
    }
    await deleteDoc(docRef);
  } catch (error) {
    console.error(`Error deleting document ${invoiceId} from Firestore:`, error);
    throw error;
  }
}

export async function clearDocumentsService(userId: string): Promise<void> {
  if (!db || !userId) throw new Error("DB not initialized or User ID missing for clearDocumentsService.");
  
  const q = query(collection(db, DOCUMENTS_COLLECTION), where("userId", "==", userId));
  const snapshot = await getDocs(q);
  if (snapshot.empty) {
    console.log(`[clearDocumentsService] No documents to delete for user ${userId}.`);
    return;
  }

  const batch = writeBatch(db);
  for (const docSnap of snapshot.docs) { // Changed doc to docSnap
    // Delete associated images from Firebase Storage before deleting the document
    if (docSnap.data().originalImagePreviewUri) {
      await deleteImageFromFirebaseStorage(docSnap.data().originalImagePreviewUri);
    }
    if (docSnap.data().compressedImageForFinalRecordUri) {
      await deleteImageFromFirebaseStorage(docSnap.data().compressedImageForFinalRecordUri);
    }
    if (docSnap.data().paymentReceiptImageUri) {
      await deleteImageFromFirebaseStorage(docSnap.data().paymentReceiptImageUri);
    }
    batch.delete(docSnap.ref);
  }
  await batch.commit();
  console.log(`[clearDocumentsService] All documents for user ${userId} have been deleted.`);
}

// --- Price Discrepancy & Product Finalization (Firestore) ---
export interface ProductPriceDiscrepancy extends Product {
  existingUnitPrice: number;
  newUnitPrice: number;
}

export interface PriceCheckResult {
  productsToSaveDirectly: Product[];
  priceDiscrepancies: ProductPriceDiscrepancy[];
}

export async function checkProductPricesBeforeSaveService(
  productsToCheck: Product[],
  userId: string
): Promise<PriceCheckResult> {
  if (!db) {
    console.error("Firestore (db) is not initialized in checkProductPricesBeforeSaveService.");
    return { productsToSaveDirectly: productsToCheck.map(p => ({...p, unitPrice: Number(p.unitPrice) || 0 })), priceDiscrepancies: [] };
  }
  if (!userId) {
    console.warn("checkProductPricesBeforeSaveService called without userId");
    return { productsToSaveDirectly: productsToCheck.map(p => ({...p, unitPrice: Number(p.unitPrice) || 0 })), priceDiscrepancies: [] };
  }

  const productsToSaveDirectly: Product[] = [];
  const priceDiscrepancies: ProductPriceDiscrepancy[] = [];

  for (const product of productsToCheck) {
    const currentProductUnitPrice = Number(product.unitPrice) || 0;
    const productWithNumericPrice = { ...product, unitPrice: currentProductUnitPrice };

    // If product ID indicates it's a completely new, unsaved product (e.g. from a fresh scan not yet matched)
    // or has no ID (should have a temp one), it should be saved directly for now.
    // The dialog flow should ideally happen before this direct save if it's truly new.
    if (!product.id || product.id.startsWith('prod-temp-') || product.id.startsWith('temp-id-') || product.id.includes('-new')) {
      productsToSaveDirectly.push(productWithNumericPrice);
      continue;
    }

    try {
      const existingProductRef = doc(db, INVENTORY_COLLECTION, product.id);
      const existingProductSnap = await getDoc(existingProductRef);

      if (existingProductSnap.exists() && existingProductSnap.data().userId === userId) {
        const existingProductData = existingProductSnap.data() as Product;
        const existingUnitPrice = Number(existingProductData.unitPrice) || 0;
        
        if (Math.abs(existingUnitPrice - productWithNumericPrice.unitPrice) > 0.001 && productWithNumericPrice.unitPrice > 0) {
          priceDiscrepancies.push({
            ...productWithNumericPrice,
            existingUnitPrice: existingUnitPrice,
            newUnitPrice: productWithNumericPrice.unitPrice,
          });
        } else {
          productsToSaveDirectly.push(productWithNumericPrice);
        }
      } else {
        // Product ID exists but not found in DB for this user (or permission issue if rules are strict)
        // Treat as new for this user, or flag an error if ID implies it should exist.
        // For now, let's assume it can be added directly if not found or if userId mismatch (rules should prevent unauthorized access later).
        productsToSaveDirectly.push(productWithNumericPrice);
      }
    } catch (error) {
      console.error(`Error checking price for product ID ${product.id || product.catalogNumber}:`, error);
      productsToSaveDirectly.push(productWithNumericPrice); 
    }
  }
  return { productsToSaveDirectly, priceDiscrepancies };
}

export interface DocumentLineItem {
  // Fields extracted directly from the document line item during AI scan
  productName?: string | null;
  catalogNumber?: string | null;
  barcode?: string | null;
  quantity: number;
  unitPrice: number; // This is the purchase_price from the document
  lineTotal: number;
  shortProductName?: string | null;
  // Optional fields that might be added if the user provides them for a new inventory item
  inventoryProductId?: string | null; // If linked to an existing inventory product
  salePrice?: number | null; // If user sets it for a new product
}


export async function finalizeSaveProductsService(
    productsFromDocument: Product[], // These are products from the UI, potentially with barcode/salePrice added
    originalFileNameFromUpload: string,
    documentType: 'deliveryNote' | 'invoice',
    userId: string,
    tempInvoiceId?: string, // This is the ID of the PENDING Firestore document
    extractedInvoiceNumber?: string | null,
    finalSupplierName?: string | null,
    extractedTotalAmount?: number | null,
    paymentDueDate?: string | Date | Timestamp | null,
    invoiceDate?: string | Date | Timestamp | null,
    paymentMethod?: string | null,
    originalImagePreviewFirebaseUrl?: string | null,
    compressedImageForFinalRecordFirebaseUrl?: string | null
): Promise<{
  finalInvoiceRecord: InvoiceHistoryItem;
  savedProductsWithFinalIds: Product[]; // Products as they are in the inventory (updated or new)
}> {
  if (!db) throw new Error("Database not initialized for finalizeSaveProductsService.");
  if (!userId) throw new Error("User authentication is required for finalizeSaveProductsService.");
  console.log(`[Backend - finalizeSaveProductsService] User: ${userId}, DocType: ${documentType}, TempID: ${tempInvoiceId}, Products from UI: ${productsFromDocument.length}`);

  const savedProductsWithFinalIds: Product[] = [];
  let calculatedInvoiceTotalAmountFromProducts = 0;
  const batchOp = writeBatch(db);

  const shouldUpdateInventory = documentType === 'deliveryNote';

  if (shouldUpdateInventory && productsFromDocument.length > 0) {
    console.log("[Backend - finalizeSaveProductsService] Processing products for inventory (deliveryNote)...");
    for (const productFromUI of productsFromDocument) {
      const quantityFromDoc = Number(productFromUI.quantity) || 0;
      let unitPriceFromDoc = Number(productFromUI.unitPrice) || 0; // This is the cost price from the document
      const lineTotalFromDoc = Number(productFromUI.lineTotal) || 0;

      if (unitPriceFromDoc === 0 && quantityFromDoc !== 0 && lineTotalFromDoc !== 0) {
        unitPriceFromDoc = parseFloat((lineTotalFromDoc / quantityFromDoc).toFixed(2));
      }
      calculatedInvoiceTotalAmountFromProducts += lineTotalFromDoc;

      let existingProductRef;
      let existingProductData: Product | undefined = undefined;
      let foundBy: 'id' | 'catalog' | 'barcode' | 'none' = 'none';
      let productToQueryId = productFromUI._originalId || productFromUI.id; // Prefer _originalId if available

      if (productToQueryId && !productToQueryId.startsWith('prod-temp-') && !productToQueryId.startsWith('temp-id-')) {
        const snap = await getDoc(doc(db, INVENTORY_COLLECTION, productToQueryId));
        if (snap.exists() && snap.data().userId === userId) {
          existingProductRef = snap.ref;
          existingProductData = { id: snap.id, ...snap.data() } as Product;
          foundBy = 'id';
        }
      }
      if (!existingProductData && productFromUI.catalogNumber && productFromUI.catalogNumber !== 'N/A') {
        const qCat = query(collection(db, INVENTORY_COLLECTION), where("userId", "==", userId), where("catalogNumber", "==", productFromUI.catalogNumber), limit(1));
        const catSnap = await getDocs(qCat);
        if (!catSnap.empty) {
          existingProductRef = catSnap.docs[0].ref;
          existingProductData = { id: catSnap.docs[0].id, ...catSnap.docs[0].data() } as Product;
          foundBy = 'catalog';
        }
      }
      if (!existingProductData && productFromUI.barcode && productFromUI.barcode.trim() !== '') {
        const qBar = query(collection(db, INVENTORY_COLLECTION), where("userId", "==", userId), where("barcode", "==", productFromUI.barcode.trim()), limit(1));
        const barSnap = await getDocs(qBar);
        if (!barSnap.empty) {
          existingProductRef = barSnap.docs[0].ref;
          existingProductData = { id: barSnap.docs[0].id, ...barSnap.docs[0].data() } as Product;
          foundBy = 'barcode';
        }
      }

      if (existingProductRef && existingProductData) {
        console.log(`[Backend - finalizeSaveProductsService] Updating existing product (found by ${foundBy}): ${existingProductData.id}, Current Qty: ${existingProductData.quantity}`);
        const currentInventoryQuantity = Number(existingProductData.quantity) || 0;
        const updatedQuantity = currentInventoryQuantity + quantityFromDoc;
        
        const updatePayload: Partial<Product> & { lastUpdated: FieldValue } = {
          quantity: updatedQuantity,
          unitPrice: unitPriceFromDoc > 0 ? unitPriceFromDoc : (existingProductData.unitPrice || 0), // Update with new cost
          lastUpdated: serverTimestamp(),
          // Keep existing description, shortName, salePrice etc. unless explicitly changed via productFromUI
          description: productFromUI.description !== undefined ? productFromUI.description : existingProductData.description,
          shortName: productFromUI.shortName !== undefined ? productFromUI.shortName : existingProductData.shortName,
          salePrice: productFromUI.salePrice !== undefined ? productFromUI.salePrice : existingProductData.salePrice,
          minStockLevel: productFromUI.minStockLevel !== undefined ? productFromUI.minStockLevel : existingProductData.minStockLevel,
          maxStockLevel: productFromUI.maxStockLevel !== undefined ? productFromUI.maxStockLevel : existingProductData.maxStockLevel,
          barcode: productFromUI.barcode !== undefined ? productFromUI.barcode : existingProductData.barcode,
          imageUrl: productFromUI.imageUrl !== undefined ? productFromUI.imageUrl : existingProductData.imageUrl,
        };
        updatePayload.lineTotal = parseFloat(((updatePayload.quantity || 0) * (updatePayload.unitPrice || 0)).toFixed(2)); // This should be based on inventory quantity and cost for internal value
        
        batchOp.update(existingProductRef, sanitizeForFirestore(updatePayload as Partial<Product>));
        savedProductsWithFinalIds.push({ ...existingProductData, ...updatePayload, id: existingProductData.id } as Product);
      } else {
        if (!productFromUI.catalogNumber && !productFromUI.description && !productFromUI.barcode) {
          console.warn("[Backend - finalizeSaveProductsService] Skipping new product due to missing identifiers:", productFromUI);
          continue;
        }
        const newProductRef = doc(collection(db, INVENTORY_COLLECTION));
        console.log(`[Backend - finalizeSaveProductsService] Creating new product: ${productFromUI.shortName || productFromUI.description}`);
        const newProductData: Product = {
          id: newProductRef.id, 
          userId,
          catalogNumber: productFromUI.catalogNumber || 'N/A',
          description: productFromUI.description || 'No Description',
          shortName: productFromUI.shortName || (productFromUI.description || 'No Description').split(' ').slice(0, 3).join(' '),
          barcode: (productFromUI.barcode && productFromUI.barcode.trim() !== '') ? productFromUI.barcode.trim() : null,
          quantity: quantityFromDoc,
          unitPrice: unitPriceFromDoc > 0 ? unitPriceFromDoc : 0, // Cost price
          salePrice: productFromUI.salePrice !== undefined ? Number(productFromUI.salePrice) : null,
          lineTotal: 0, // This should be calculated based on inventory for internal value, not line total from doc
          minStockLevel: productFromUI.minStockLevel !== undefined ? Number(productFromUI.minStockLevel) : null,
          maxStockLevel: productFromUI.maxStockLevel !== undefined ? Number(productFromUI.maxStockLevel) : null,
          imageUrl: productFromUI.imageUrl || null,
          lastUpdated: serverTimestamp(),
        };
        newProductData.lineTotal = parseFloat(((newProductData.quantity || 0) * (newProductData.unitPrice || 0)).toFixed(2));

        batchOp.set(newProductRef, sanitizeForFirestore(newProductData));
        savedProductsWithFinalIds.push({ ...newProductData, id: newProductRef.id });
      }
    }
  } else if (documentType === 'invoice') {
    console.log("[Backend - finalizeSaveProductsService] Tax Invoice: Products not added/updated in inventory.");
    productsFromDocument.forEach(p => calculatedInvoiceTotalAmountFromProducts += (Number(p.lineTotal) || 0));
  }

  const finalInvoiceTotalAmount = (extractedTotalAmount !== undefined && extractedTotalAmount !== null && !isNaN(extractedTotalAmount) && extractedTotalAmount > 0)
                                  ? extractedTotalAmount
                                  : parseFloat(calculatedInvoiceTotalAmountFromProducts.toFixed(2));

  let finalGeneratedFileName = originalFileNameFromUpload;
  if (finalSupplierName && finalSupplierName.trim() !== '') {
    finalGeneratedFileName = finalSupplierName.trim();
    if (extractedInvoiceNumber && extractedInvoiceNumber.trim() !== '') {
      finalGeneratedFileName += `_${extractedInvoiceNumber.trim()}`;
    }
  } else if (extractedInvoiceNumber && extractedInvoiceNumber.trim() !== '') {
    finalGeneratedFileName = `Invoice_${extractedInvoiceNumber.trim()}`;
  }
  finalGeneratedFileName = finalGeneratedFileName.replace(/[/\\?%*:|"<>]/g, '-').substring(0,100);
  
  let docRef;
  let isNewDocumentCreation = true;
  let existingUploadTimeForUpdate: Timestamp | FieldValue = serverTimestamp();
  let existingPaymentReceiptUri: string | null | undefined = undefined;
  let existingErrorMessage: string | null | undefined = null;

  if (tempInvoiceId) { // tempInvoiceId is the Firestore ID of the PENDING document
    docRef = doc(db, DOCUMENTS_COLLECTION, tempInvoiceId);
    try {
      const existingDocSnap = await getDoc(docRef);
      if (existingDocSnap.exists()) {
        isNewDocumentCreation = false; 
        existingUploadTimeForUpdate = existingDocSnap.data().uploadTime || serverTimestamp();
        existingPaymentReceiptUri = existingDocSnap.data().paymentReceiptImageUri;
        existingErrorMessage = existingDocSnap.data().errorMessage;
        // Preserve existing image URIs if new ones are not provided
        if (originalImagePreviewFirebaseUrl === undefined && existingDocSnap.data().originalImagePreviewUri) {
          originalImagePreviewFirebaseUrl = existingDocSnap.data().originalImagePreviewUri;
        }
        if (compressedImageForFinalRecordFirebaseUrl === undefined && existingDocSnap.data().compressedImageForFinalRecordUri) {
          compressedImageForFinalRecordFirebaseUrl = existingDocSnap.data().compressedImageForFinalRecordUri;
        }
         console.log(`[Backend - finalizeSaveProductsService] Found existing PENDING document ${tempInvoiceId} to update.`);
      } else {
         console.warn(`[Backend - finalizeSaveProductsService] PENDING document ${tempInvoiceId} not found. Creating new one.`);
         docRef = doc(collection(db, DOCUMENTS_COLLECTION)); // Create a new ref
      }
    } catch (e) { 
        console.error(`Error fetching existing pending document ${tempInvoiceId}:`, e);
        // Fallback to creating a new document if fetch fails unexpectedly
        docRef = doc(collection(db, DOCUMENTS_COLLECTION));
    }
  } else { 
    docRef = doc(collection(db, DOCUMENTS_COLLECTION));
     console.log(`[Backend - finalizeSaveProductsService] No tempInvoiceId provided. Creating new document ref: ${docRef.id}`);
  }

  const convertToTimestampIfValid = (dateVal: any): Timestamp | null => {
    if (!dateVal) return null;
    if (dateVal instanceof Date && isValid(dateVal)) return Timestamp.fromDate(dateVal);
    if (typeof dateVal === 'string' && isValid(parseISO(dateVal))) return Timestamp.fromDate(parseISO(dateVal));
    if (dateVal instanceof Timestamp) return dateVal;
    return null;
  };

  const documentDataForFirestore: Omit<InvoiceHistoryItem, 'id' | 'uploadTime'> & { uploadTime: Timestamp | FieldValue } = {
    userId,
    generatedFileName: finalGeneratedFileName,
    originalFileName: originalFileNameFromUpload,
    uploadTime: isNewDocumentCreation ? serverTimestamp() : existingUploadTimeForUpdate,
    status: 'completed', // Mark as completed upon final save
    documentType: documentType,
    invoiceNumber: extractedInvoiceNumber || null,
    supplierName: finalSupplierName || null,
    totalAmount: !isNaN(finalInvoiceTotalAmount) ? finalInvoiceTotalAmount : null,
    paymentStatus: 'unpaid', 
    paymentDueDate: convertToTimestampIfValid(paymentDueDate),
    invoiceDate: convertToTimestampIfValid(invoiceDate),
    paymentMethod: paymentMethod || null,
    errorMessage: existingErrorMessage || null, // Preserve existing error if any, or set to null
    paymentReceiptImageUri: existingPaymentReceiptUri === undefined ? null : existingPaymentReceiptUri,
    originalImagePreviewUri: originalImagePreviewFirebaseUrl || null,
    compressedImageForFinalRecordUri: compressedImageForFinalRecordFirebaseUrl || null,
    linkedDeliveryNoteId: null,
  };
  
  batchOp.set(docRef, sanitizeForFirestore(documentDataForFirestore), { merge: !isNewDocumentCreation });

  let finalUploadTimeForReturn: string;
  if (documentDataForFirestore.uploadTime instanceof Timestamp) {
    finalUploadTimeForReturn = documentDataForFirestore.uploadTime.toDate().toISOString();
  } else {
    // If it's a serverTimestamp(), we can't get the exact time until after commit.
    // For immediate UI update, use current client time. Firestore will store server time.
    finalUploadTimeForReturn = new Date().toISOString();
  }
  
  const finalInvoiceRecord: InvoiceHistoryItem = { 
    ...(documentDataForFirestore as Omit<InvoiceHistoryItem, 'id' | 'uploadTime' | 'invoiceDate' | 'paymentDueDate'>), 
    id: docRef.id, 
    uploadTime: finalUploadTimeForReturn,
    invoiceDate: documentDataForFirestore.invoiceDate instanceof Timestamp ? documentDataForFirestore.invoiceDate.toDate().toISOString() : null,
    paymentDueDate: documentDataForFirestore.paymentDueDate instanceof Timestamp ? documentDataForFirestore.paymentDueDate.toDate().toISOString() : null,
  };

  try {
    console.log("[Backend - finalizeSaveProductsService] Committing batch to Firestore...");
    await batchOp.commit();
    console.log("[Backend - finalizeSaveProductsService] Batch commit successful. Final Doc ID:", finalInvoiceRecord.id);
    
    // Clear temporary localStorage data only *after* successful Firestore commit
    if (tempInvoiceId && tempInvoiceId.startsWith(`pending-inv-${userId}_`)) {
      const uniqueScanIdToClear = tempInvoiceId.substring(`pending-inv-${userId}_`.length);
      clearTemporaryScanData(uniqueScanIdToClear, userId);
    }
  } catch (error: any) {
    console.error("[Backend - finalizeSaveProductsService] Error committing batch to Firestore:", error);
    throw new Error(`Failed to save document and products to Firestore: ${error.message}`);
  }
  return { finalInvoiceRecord, savedProductsWithFinalIds };
}

// --- Supplier Management (Firestore) ---
export async function getSupplierSummariesService(userId: string): Promise<SupplierSummary[]> {
  if (!db) {
    console.error("Firestore (db) is not initialized in getSupplierSummariesService.");
    return [];
  }
  if (!userId) {
    console.warn("getSupplierSummariesService called without userId");
    return [];
  }

  const suppliersQuery = query(collection(db, SUPPLIERS_COLLECTION), where("userId", "==", userId));
  const documentsQuery = query(collection(db, DOCUMENTS_COLLECTION), where("userId", "==", userId), where("status", "==", "completed"));

  try {
    const [suppliersSnapshot, documentsSnapshot] = await Promise.all([
      getDocs(suppliersQuery),
      getDocs(documentsQuery)
    ]);

    const supplierMap = new Map<string, SupplierSummary>();

    suppliersSnapshot.docs.forEach(docSnap => { // Changed doc to docSnap
      const data = docSnap.data();
      const createdAtTimestamp = data.createdAt instanceof Timestamp ? data.createdAt : serverTimestamp(); // Handle potential server timestamp
      let lastActivityDateTimestamp: Timestamp | string | null = null;
      if (data.lastActivityDate instanceof Timestamp) {
        lastActivityDateTimestamp = data.lastActivityDate.toDate().toISOString();
      } else if (typeof data.lastActivityDate === 'string') {
        lastActivityDateTimestamp = data.lastActivityDate; // Assume it's already ISO string
      }
      
      // Ensure supplier name is a non-empty string before adding to map
      if (data.name && typeof data.name === 'string' && data.name.trim() !== '') {
        supplierMap.set(data.name, {
          id: docSnap.id, // Use docSnap.id
          userId,
          name: data.name,
          phone: data.phone || null,
          email: data.email || null,
          paymentTerms: data.paymentTerms || null,
          invoiceCount: 0,
          totalSpent: 0,
          lastActivityDate: lastActivityDateTimestamp,
          createdAt: createdAtTimestamp,
        });
      } else {
        console.warn(`Supplier document ${docSnap.id} for user ${userId} is missing a valid name.`);
      }
    });

    documentsSnapshot.docs.forEach(docSnap => { // Changed doc to docSnap
      const docData = docSnap.data() as InvoiceHistoryItem; 
      if (docData.supplierName && typeof docData.supplierName === 'string' && docData.status === 'completed') {
        let supplierEntry = supplierMap.get(docData.supplierName);

        // If supplier from document doesn't exist in the suppliers collection,
        // we might decide to create it on-the-fly or just log a warning.
        // For now, let's assume we only update existing suppliers found via the map.
        if (supplierEntry) {
            supplierEntry.invoiceCount += 1;
            supplierEntry.totalSpent += (docData.totalAmount || 0);

            let docUploadDate: Date | null = null;
            if (docData.uploadTime) {
                if (docData.uploadTime instanceof Timestamp) docUploadDate = docData.uploadTime.toDate();
                else if (typeof docData.uploadTime === 'string' && isValid(parseISO(docData.uploadTime))) docUploadDate = parseISO(docData.uploadTime);
            }
            
            let currentLastActivityDate: Date | null = null;
            if (supplierEntry.lastActivityDate) {
                 if(supplierEntry.lastActivityDate instanceof Timestamp) currentLastActivityDate = supplierEntry.lastActivityDate.toDate();
                 else if(typeof supplierEntry.lastActivityDate === 'string' && isValid(parseISO(supplierEntry.lastActivityDate))) currentLastActivityDate = parseISO(supplierEntry.lastActivityDate);
            }

            if (docUploadDate && (!currentLastActivityDate || docUploadDate > currentLastActivityDate)) {
              supplierEntry.lastActivityDate = docUploadDate.toISOString();
            }
            supplierMap.set(docData.supplierName, supplierEntry);
        } else {
            // Optionally handle cases where a supplier in a document doesn't exist in the suppliers collection
            console.warn(`Supplier "${docData.supplierName}" from document ${docSnap.id} not found in main suppliers list for user ${userId}.`);
        }
      }
    });
    return Array.from(supplierMap.values()).sort((a,b) => (a.name || "").localeCompare(b.name || ""));
  } catch (error) {
    console.error("Error fetching supplier summaries from Firestore:", error);
    throw error;
  }
}

export async function createSupplierService(name: string, contactInfo: { phone?: string; email?: string, paymentTerms?: string }, userId: string): Promise<SupplierSummary> {
  if (!db) throw new Error("Database not initialized for createSupplierService.");
  if (!userId) throw new Error("User authentication is required for createSupplierService.");
  const normalizedName = name.trim();
  if (!normalizedName) throw new Error("Supplier name cannot be empty.");

  const q = query(collection(db, SUPPLIERS_COLLECTION), where("userId", "==", userId), where("name", "==", normalizedName));
  const existing = await getDocs(q);
  if (!existing.empty) throw new Error(`Supplier with name "${normalizedName}" already exists.`);

  const newSupplierRef = doc(collection(db, SUPPLIERS_COLLECTION));
  const newSupplierData: Omit<SupplierSummary, 'id' | 'createdAt' | 'lastActivityDate' | 'invoiceCount' | 'totalSpent'> & { userId: string, createdAt: FieldValue } = {
    name: normalizedName,
    phone: contactInfo.phone?.trim() || null,
    email: contactInfo.email?.trim() || null,
    paymentTerms: contactInfo.paymentTerms?.trim() || null,
    userId: userId, 
    createdAt: serverTimestamp(),
  };
  console.log(`[Backend - createSupplierService] Attempting to save new supplier with data:`, newSupplierData, `for userId: ${userId}`);
  await setDoc(newSupplierRef, sanitizeForFirestore(newSupplierData));

  const now = Timestamp.now(); 
  return {
      id: newSupplierRef.id,
      userId,
      name: normalizedName,
      phone: newSupplierData.phone,
      email: newSupplierData.email,
      paymentTerms: newSupplierData.paymentTerms,
      invoiceCount: 0, 
      totalSpent: 0,   
      lastActivityDate: null, 
      createdAt: now,  
  };
}

export async function deleteSupplierService(supplierId: string, userId: string): Promise<void> {
  if (!db || !userId) throw new Error("DB not initialized or User ID missing for deleteSupplierService.");
  
  const supplierRef = doc(db, SUPPLIERS_COLLECTION, supplierId);
  const supplierDoc = await getDoc(supplierRef);
  if (!supplierDoc.exists() || supplierDoc.data().userId !== userId) {
    throw new Error(`Supplier not found or permission denied for deletion for supplier ID: ${supplierId}`);
  }
  await deleteDoc(supplierRef);
}

export async function clearSuppliersService(userId: string): Promise<void> {
  await deleteCollectionByUserId(SUPPLIERS_COLLECTION, userId);
}

export async function updateSupplierContactInfoService(supplierId: string, contactInfo: { phone?: string | null; email?: string | null; paymentTerms?: string | null }, userId: string): Promise<void> {
  if (!db || !userId) throw new Error("DB not initialized or User ID missing.");

  const supplierRef = doc(db, SUPPLIERS_COLLECTION, supplierId);
  const existingDoc = await getDoc(supplierRef);
  if (!existingDoc.exists() || existingDoc.data().userId !== userId) {
    throw new Error("Supplier not found or permission denied for update.");
  }

  const updatePayload: Partial<Pick<SupplierSummary, 'phone' | 'email' | 'paymentTerms'>> = {};
  let hasChanges = false;

  if (contactInfo.hasOwnProperty('phone')) {
    const newPhone = contactInfo.phone?.trim() || null;
    if (newPhone !== (existingDoc.data().phone || null)) { 
        updatePayload.phone = newPhone;
        hasChanges = true;
    }
  }
  if (contactInfo.hasOwnProperty('email')) {
    const newEmail = contactInfo.email?.trim() || null;
     if (newEmail !== (existingDoc.data().email || null)) {
        updatePayload.email = newEmail;
        hasChanges = true;
    }
  }
  if (contactInfo.hasOwnProperty('paymentTerms')) {
    const newPaymentTerms = contactInfo.paymentTerms?.trim() || null;
    if (newPaymentTerms !== (existingDoc.data().paymentTerms || null)) {
        updatePayload.paymentTerms = newPaymentTerms;
        hasChanges = true;
    }
  }
  
  if (hasChanges) {
    await updateDoc(supplierRef, sanitizeForFirestore(updatePayload));
  }
}

// --- User Settings (Firestore) ---
export async function saveUserSettingsService(settings: Partial<Omit<UserSettings, 'userId'>>, userId: string): Promise<void> {
    if (!db || !userId) throw new Error("DB not initialized or User ID missing for saveUserSettingsService.");
    const userSettingsRef = doc(db, USER_SETTINGS_COLLECTION, userId);
    
    const settingsToSave: Partial<UserSettings> = JSON.parse(JSON.stringify(settings)); // Deep clone

    // Sanitize nested objects or ensure they default correctly
    if (settingsToSave.hasOwnProperty('accountantSettings')) {
        settingsToSave.accountantSettings = settingsToSave.accountantSettings ? sanitizeForFirestore(settingsToSave.accountantSettings) : { name: null, email: null, phone: null };
    }
    if (settingsToSave.hasOwnProperty('posConfig')) {
        settingsToSave.posConfig = settingsToSave.posConfig ? sanitizeForFirestore(settingsToSave.posConfig) : {};
    }
    if (settingsToSave.hasOwnProperty('kpiPreferences')) {
        settingsToSave.kpiPreferences = settingsToSave.kpiPreferences ? sanitizeForFirestore(settingsToSave.kpiPreferences) : { visibleKpiIds: [], kpiOrder: [] };
    }
    if (settingsToSave.hasOwnProperty('quickActionPreferences')) {
        settingsToSave.quickActionPreferences = settingsToSave.quickActionPreferences ? sanitizeForFirestore(settingsToSave.quickActionPreferences) : { visibleQuickActionIds: [], quickActionOrder: [] };
    }
    
    // Ensure fields meant to be null are null, not undefined
    if (settingsToSave.hasOwnProperty('monthlyBudget') && settingsToSave.monthlyBudget === undefined) settingsToSave.monthlyBudget = null;
    if (settingsToSave.hasOwnProperty('reminderDaysBefore') && settingsToSave.reminderDaysBefore === undefined) settingsToSave.reminderDaysBefore = null;
    if (settingsToSave.hasOwnProperty('posSystemId') && settingsToSave.posSystemId === undefined) settingsToSave.posSystemId = null;
    
    delete (settingsToSave as any).userId; 
    
    console.log("[saveUserSettingsService] Saving settings for user:", userId, settingsToSave);
    await setDoc(userSettingsRef, sanitizeForFirestore(settingsToSave), { merge: true });
}

export async function getUserSettingsService(userId: string): Promise<UserSettings> {
    const defaultSettings: UserSettings = {
        userId: userId || '', 
        reminderDaysBefore: 3, 
        posSystemId: null,
        posConfig: {},
        accountantSettings: { name: null, email: null, phone: null },
        monthlyBudget: null,
        kpiPreferences: { visibleKpiIds: ['totalItems', 'inventoryValue', 'grossProfit', 'currentMonthExpenses', 'lowStock', 'amountToPay'], kpiOrder: ['totalItems', 'inventoryValue', 'grossProfit', 'currentMonthExpenses', 'lowStock', 'amountToPay', 'documentsProcessed30d', 'averageInvoiceValue', 'suppliersCount'] }, 
        quickActionPreferences: { visibleQuickActionIds: ['addExpense', 'addProduct', 'openInvoices', 'latestDocument'], quickActionOrder: ['addExpense', 'addProduct', 'openInvoices', 'latestDocument', 'addSupplier'] } 
    };
    if (!db || !userId) {
      console.warn("getUserSettingsService called without db or userId, returning defaults.");
      return defaultSettings;
    }
    
    const userSettingsRef = doc(db, USER_SETTINGS_COLLECTION, userId);
    const docSnap = await getDoc(userSettingsRef);

    if (docSnap.exists()) {
        const data = docSnap.data();
        return { 
            ...defaultSettings, 
            ...data,            
            userId,             
            accountantSettings: data.accountantSettings ? { 
                name: data.accountantSettings.name || null,
                email: data.accountantSettings.email || null,
                phone: data.accountantSettings.phone || null,
            } : defaultSettings.accountantSettings,
            posConfig: data.posConfig || defaultSettings.posConfig,
            kpiPreferences: data.kpiPreferences || defaultSettings.kpiPreferences,
            quickActionPreferences: data.quickActionPreferences || defaultSettings.quickActionPreferences,
            monthlyBudget: data.monthlyBudget === undefined ? null : (data.monthlyBudget ?? null), 
            reminderDaysBefore: data.reminderDaysBefore === undefined ? defaultSettings.reminderDaysBefore : (data.reminderDaysBefore ?? null),
        };
    }
    console.log(`[getUserSettingsService] No settings found for user ${userId}, returning defaults.`);
    return defaultSettings; 
}

// --- Other Expenses & Categories (Firestore) ---
export async function getOtherExpensesService(userId: string): Promise<OtherExpense[]> {
  if (!db || !userId) {
    console.warn("getOtherExpensesService called without db or userId, returning empty array.");
    return [];
  }
  const expensesQuery = query(collection(db, OTHER_EXPENSES_COLLECTION), where("userId", "==", userId), orderBy("date", "desc"));
  try {
    const snapshot = await getDocs(expensesQuery);
    return snapshot.docs.map(docSnap => { // Changed doc to docSnap
        const data = docSnap.data();
        return {
            id: docSnap.id, ...data,
            date: data.date instanceof Timestamp ? data.date.toDate().toISOString() : data.date, 
        } as OtherExpense;
    });
  } catch (error) {
    console.error("Error fetching other expenses from Firestore:", error);
    if ((error as any).message && (error as any).message.includes("The query requires an index")) {
        console.error("Firestore missing index error for otherExpenses. Check browser console for link to create it.");
    }
    throw error;
  }
}

export async function saveOtherExpenseService(expenseData: Omit<OtherExpense, 'id' | 'userId'> & {id?: string}, userId: string): Promise<string> {
  if (!db || !userId) throw new Error("User authentication required for saveOtherExpenseService.");
  
  const { id: expenseId, ...dataToProcess } = expenseData;

  let dateForFirestore: Timestamp | FieldValue;
  if (dataToProcess.date instanceof Timestamp) {
    dateForFirestore = dataToProcess.date;
  } else if (typeof dataToProcess.date === 'string' && isValid(parseISO(dataToProcess.date))) {
    dateForFirestore = Timestamp.fromDate(parseISO(dataToProcess.date));
  } else if (dataToProcess.date instanceof Date && isValid(dataToProcess.date)) {
    dateForFirestore = Timestamp.fromDate(dataToProcess.date);
  } else {
    dateForFirestore = serverTimestamp(); // Fallback if date is invalid or not provided
  }

  const dataToSave: any = { 
    ...dataToProcess,
    userId,
    date: dateForFirestore, 
    _internalCategoryKey: dataToProcess._internalCategoryKey || null, 
    categoryId: dataToProcess.categoryId || null, 
  };

  if (expenseId) { 
    const docRef = doc(db, OTHER_EXPENSES_COLLECTION, expenseId);
    await updateDoc(docRef, sanitizeForFirestore({ ...dataToSave, lastUpdatedAt: serverTimestamp() }));
    return expenseId;
  } else { 
    const newDocRef = doc(collection(db, OTHER_EXPENSES_COLLECTION));
    delete dataToSave.id; // Ensure no 'id' field is in the data for addDoc/setDoc on new ref
    await setDoc(newDocRef, sanitizeForFirestore({ ...dataToSave, createdAt: serverTimestamp() }));
    return newDocRef.id;
  }
}

export async function deleteOtherExpenseService(expenseId: string, userId: string): Promise<void> {
    if (!db || !userId) throw new Error("User authentication required for deleteOtherExpenseService.");
    const docRef = doc(db, OTHER_EXPENSES_COLLECTION, expenseId);
    const docSnap = await getDoc(docRef); 
    if (!docSnap.exists() || docSnap.data().userId !== userId) {
        throw new Error("Expense not found or permission denied.");
    }
    await deleteDoc(docRef);
}

export async function clearOtherExpensesService(userId: string): Promise<void> {
  await deleteCollectionByUserId(OTHER_EXPENSES_COLLECTION, userId);
}

export async function getExpenseCategoriesService(userId: string): Promise<ExpenseCategory[]> {
  if (!db || !userId) {
    console.warn("getExpenseCategoriesService called without db or userId, returning empty array.");
    return [];
  }
  const categoriesQuery = query(collection(db, EXPENSE_CATEGORIES_COLLECTION), where("userId", "==", userId), orderBy("name"));
  try {
    const snapshot = await getDocs(categoriesQuery);
    return snapshot.docs.map(docSnap => ({ // Changed doc to docSnap
        id: docSnap.id, 
        ...docSnap.data(), 
        createdAt: docSnap.data().createdAt instanceof Timestamp ? docSnap.data().createdAt : serverTimestamp() 
    } as ExpenseCategory));
  } catch (error) {
     console.error("Error fetching expense categories from Firestore:", error);
     if ((error as any).message && (error as any).message.includes("The query requires an index")) {
        console.error("Firestore missing index error for expenseCategories. Check browser console for link to create it.");
    }
    throw error;
  }
}

export async function saveExpenseCategoryService(categoryData: Omit<ExpenseCategory, 'id' | 'userId' | 'createdAt'>, userId: string): Promise<string> {
  if (!db || !userId) throw new Error("User authentication required for saveExpenseCategoryService.");
  if (!categoryData.name || !categoryData.internalKey) throw new Error("Category name and internalKey are required.");

  const q = query(collection(db, EXPENSE_CATEGORIES_COLLECTION), where("userId", "==", userId), where("internalKey", "==", categoryData.internalKey));
  const existing = await getDocs(q);
  if (!existing.empty) {
    throw new Error(`Expense category with key "${categoryData.internalKey}" already exists for this user.`);
  }

  const newDocRef = doc(collection(db, EXPENSE_CATEGORIES_COLLECTION));
  const dataToSave: Omit<ExpenseCategory, 'id'> = { 
      ...categoryData, 
      userId, 
      createdAt: serverTimestamp(), 
      isFixed: categoryData.isFixed ?? false, 
      defaultAmount: categoryData.defaultAmount ?? null, 
  };
  await setDoc(newDocRef, sanitizeForFirestore(dataToSave));
  return newDocRef.id;
}

export async function clearExpenseCategoriesService(userId: string): Promise<void> {
  await deleteCollectionByUserId(EXPENSE_CATEGORIES_COLLECTION, userId);
}

// --- Temporary Data Management for Uploads (localStorage & potential Firebase Storage cleanup) ---
export function clearTemporaryScanData(uniqueScanId?: string, userId?: string) {
    if (typeof window === 'undefined' || !userId) return;
    if (!uniqueScanId) {
      console.warn("[clearTemporaryScanData] Called without uniqueScanId for user:", userId);
      return;
    }
    try {
      const dataKey = getStorageKey(TEMP_DATA_KEY_PREFIX, `${userId}_${uniqueScanId}`);
      localStorage.removeItem(dataKey);
      console.log(`[clearTemporaryScanData] Cleared localStorage scan result: ${dataKey}`);
    } catch (error) {
        console.error(`Error removing temp localStorage key for UserID: ${userId}, ScanID: ${uniqueScanId}`, error);
    }
}

export function clearOldTemporaryScanData(emergencyClear: boolean = false, userIdToClear?: string) {
  if (typeof window === 'undefined') return;
  const now = Date.now();
  const EXPIRY_DURATION_MS = 24 * 60 * 60 * 1000; // 24 hours
  let itemsCleared = 0;
  const keysToRemove: string[] = [];

  for (let i = 0; i < localStorage.length; i++) {
    const key = localStorage.key(i);
    if (key && key.startsWith(TEMP_DATA_KEY_PREFIX)) { // Only clear JSON scan results
        if (userIdToClear && !key.includes(`_${userIdToClear}_`)) {
            continue;
        }
        const parts = key.split('_');
        const timestampString = parts.find(part => /^\d{13,}$/.test(part));
        const timestamp = timestampString ? parseInt(timestampString, 10) : null;

        if (emergencyClear && (userIdToClear || !key.includes('_SHARED_OR_NO_USER_'))) {
             keysToRemove.push(key);
        } else if (timestamp && !isNaN(timestamp) && (now - timestamp > EXPIRY_DURATION_MS)) {
          keysToRemove.push(key);
        }
    }
  }
  keysToRemove.forEach(key => {
    try { localStorage.removeItem(key); itemsCleared++; } catch (e) { console.error(`Error removing key ${key}:`, e); }
  });
  if (itemsCleared > 0) console.log(`Cleared ${itemsCleared} old/emergency temp scan result items from localStorage (User: ${userIdToClear || 'All Relevant'}).`);
}
